### ISSUE TITLE
Scheduler, add name of patient at modal of event

### ISSUE THREAD

**Issue by arditazo3** [trewpog/LoremIspum#1]
Should add **new components** at modal create/update, 
- name of patient (selected from a search textfield, something like search button at new patient) 
- type appointment

After done every event need to display:
- name of patient
- title
- content
- time

( every event should have different color, 
reference link: http://stackoverflow.com/questions/22038755/change-the-background-color-of-the-events-in-fullcalendar  )

**Comment by sc001cs** [comment]
Done the first ticket!
